#!/bin/sh
#
# pre-commit hook to run check-patch on the output and stop any commits
# that do not pass. Note, only for git-commit, and not for any of the
# other scenarios
#
# Copyright 2010 Ben Dooks, <ben-linux@fluff.org>

if git rev-parse --verify HEAD 2>/dev/null >/dev/null
then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=e05c4dac7d13f7704c2bb4df7dd690170b4df736
fi

git diff --cached $against -- | ./../../kernel/scripts/checkpatch.pl --no-signoff -

